### ISSUE TITLE
email/復号化したpasswordを返却するAPIを作成する

### ISSUE THREAD

**Issue by sizuhiko** [its-succ/dakoku-web#8]
* 同一GAE内（同一プロジェクトIDのホスト名）からのアクセスに制限する

**Comment by t-kunou** [comment]
しょーもないツッコミですが
✗ 複合
○ 復号

**Comment by sizuhiko** [comment]
GAE内からのアクセスかどうか判定するのは難しそう。APIキー使うしかないかなぁ...

**Comment by sizuhiko** [comment]
真面目にやると、こういうことか...
https://cloud.google.com/endpoints/docs/service-to-service-auth?hl=ja

**Comment by sizuhiko** [comment]
本当はこのあたりの説明どおりやりたいけど、認証については？
https://cloud.google.com/appengine/docs/standard/java/designing-microservice-api?hl=ja

**Comment by sizuhiko** [comment]
これかーーー

> すべてのマイクロサービスを App Engine で展開している場合は、受信した X-Appengine-Inbound-Appid ヘッダーを検査することも可能です。このヘッダーは、別の App Engine プロジェクトに対するリクエストを実行する際に Urlfetch インフラで追加されるもので、外部から設定することはできません。セキュリティ要件によっては、この受信ヘッダーを検査してセキュリティ ポリシーを適用することができます。

https://cloud.google.com/appengine/docs/standard/java/microservice-performance?hl=ja

**Comment by sizuhiko** [comment]
2nd Genはダメなのか...
https://groups.google.com/forum/?hl=Es#!topic/google-appengine-go/tKdm30iwXQo

**Comment by sizuhiko** [comment]
あれれ、Node.jsの公式ドキュメントみたら、やっぱり `X-Appengine-Inbound-Appid` 入るっぽいので、ちゃんとスパイクして確認する
https://cloud.google.com/appengine/docs/standard/nodejs/reference/request-response-headers#request_headers

**Comment by sizuhiko** [comment]
`X-Appengine-Inbound-Appid` はやっぱり入らない（予想どおり）。
これはドキュメントを1st Genベースでコピペしたからなのか、1st Genから呼び出されると入っていることがあるよ、ということなのか微妙なので、深入りはしない

**Comment by sizuhiko** [comment]
ということで、良案としては

IoT Device -- {Cloud IoT Core} --> IoT Cloud Functions -- {AppEngine Queue(Cloud Tasks) w/cardNumber } --> default[service] -- {AppEngine Queue(Cloud Tasks) w/email&password } -->  script[service]

のように連携することで、プライベート呼び出しができるので、認証が楽になる。
- Cloud FunctionsはPub/Subトリガーを作れるので、IoT Core -> Pub/Subからだけ呼び出し可能なエンドポイントにできる
- GAEのエンドポイントは `X-AppEngine-QueueName` が入っていたらタスクキューからのリクエストなので処理し、それ以外はURLを直接叩かれた可能性があるので拒否する

**Comment by sizuhiko** [comment]
[システム構成図](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=dakoku-structure-draw.io.xml#R7Vxdb6M4FP01kWYfEoGBfDw2mXZnpY62o0TanafIAYd4SjBrTJvOr18bzKehSRqSRqWpVMGNgWuf63PuNZCeMdvu%2FqQw2HwnDvJ6QHN2PeNrD4CxNeT%2FheElMVgTIzG4FDuJSc8Nc%2FwbSaMmrRF2UFhqyAjxGA7KRpv4PrJZyQYpJc%2FlZmvila8aQBcphrkNPdX6D3bYRnYLjHL7N4TdTXplfThJvtnCtLHsSbiBDnkumIzbnjGjhLBka7ubIU%2BMXTouyXF3Dd9mjlHks0MOINMosMNgsvHptk%2BQ%2BfcO%2F%2Bqnwxyyl7THyOEDIHcJZRviEh96t7l1SknkO0icVuN7G7b1%2BKbON38hxl4khjBihJvyM9wTEsh23GP68q88Pt75KXYGFt9N%2FBFONPZTmkISURu90jkZegxSF7FX2o0zNHgUI7JF3CF%2BHEUeZPip7AeU8eRm7bJDHwjmHgJNhr6hybGVkT%2FRymdI3JIH5bjxjYIXuSlG8xhkpcNP0ItkF77%2FWCy%2BzP9QEGdox8pAUhTi33AVNxAYBcLL2G9r2rO%2Bcgv0sOtzg81RQZQbnhBlmM%2BbG%2FnFFjtOHC0eXCFvCu1HN46bGfEIja9rrONPhrk4A9rVzWrpST6XitHwSlyrmMrT97UBKIHTlxd8K%2BZpE7Jeh%2BgseA4VOB34SB6j%2FopA6iiYhoySR1QYbCf%2B8MFeY8%2BrAyHjJxEAyeEp4%2BmlSS%2F24CokXsTQDbXlfI%2Bt2R5IgX8gIWaY1IbKfaVBFjJ7g2tFGCNb4WcAbey792jNZKiuic8K3ZvEH2lPXRXePW8wQ3N%2BuLA8c%2B3KzzaVZ4970RibCiM1RptZJoJ09znXk5E0bYpSomnN4VeKrmNDaaSEkhI%2BDgw3GcOXZ2GF8yvhNLLEXxZB6Tc%2B8VESY4E4x3bnimxh4NoBGNhkG%2FBQWiLfxT5aYlsEw5QPL5OXOAiC5knTiIsQnCoSVg0Sppk2PFES%2BsAqRYIOBiOrfJLzEYhutin1r0n4oWlAi1I%2FPlDqdXCi1p808cyxMvMeolUPDD2hvyvKt1yWDcwHV2hz39ysKDRoZwrqRu1pzz%2F%2FVOyvUbRbkLusdpNDPFT1TtdraHZ4Lr2bKCM%2F80jkqPPuL7Lg7WaEIvU7mW056AnbvCDdP2ffLKGWPjbvjOMkVPRniQlb2sL5knpW0zCajPjhWZgXJ1fN9FHOwawjcrC3C3tDyfbSLOymqUacMWmFU8qi3tcng8uJ%2BqhNUX8H4dbBocptvatyqznzPFp9CaJw0416evQq5fN6WjOMsrKeqNcXmDugK4psjK5MkdMkbL8kx%2Fnx3bwuS04U%2BSqVOIhWIXf54%2BtwUz3VOSEGwzaF%2BMqqa906VKRPXUo%2FjVWszhD6sLKQNK5hdHBRRlfXpxsY%2FS7ybUFxNTWUrLF4HXOVrL7OPO8AsTek290j9lYrrJzYYy7Pqf2diP3QdVPQcD%2FtQsTembUzyypn6vp4rMyzSe0tinMNvbp4toDho8rPPyIU1a2LnT9Lf8MtJ8a7sPwv8fjKuFyLP%2B1y%2BfGrZQao4fITK%2FoGLh9ejMnHrTL5DrMCkfO9n9fJ8WkauJ%2FjG2q5y3B86mYHON4sTwEw1tXkXbtk8p72oTD2N0GgcvZtfIe%2BhuPRGkbetSXtMAjkMwXXxvFnyNebErTu5euTD5yvp5y4n8sb7q5fiMtBZ7i8kq8bE3Uh5qL5OlBX1o%2FL1xmC234YYIrPyuefSfs%2BQm%2FIxjqWtBu6EnMXfUB9oJV5P5eBB0Qx7524WRtfpk2aNw%2BkebOBnU5Ee5TezUhf2tArmeeZn11P%2B98B%2FajUAmbdQv5lawH1JspxtUCyhh%2FaFAefFcF7VgQNKWDnKgLjgOfdM27Q4hAuhGQhAGsD7ei3HLJ3F6rRwoT8TEnEPB6gs%2Bx9Nq1X83RQNbz56GEbDfj8sVHAwoFPHLR0kc81yq5Jvu6mN2ZbtyIrbzdkzxQV42qoxlX6eG%2FrBGaoK9afcLcGtwUqBY%2FxznCbh6wbfsLdEtzWe89uU12qXPCKdS4L1grwe1Eq4F8PmIpNXZhUENC06e0dqAES%2Fo4oSp4maAefkVHGx5yYCj51rzQZoKq%2F7SH0kd8zMuXyypXfMDfVJP7bYvEwV5D5gI8qm6%2B%2FWNTnsWOli8RpOmqeluOeP4c11WW948kOhkEiOmu8E3NtP%2FvVkp2Cf62oVanPxozi3WAlfpIhPqoNddIH5bqiNhsZpY2KBDh6CwHy3fz3GhJo8x%2B9MG7%2FBw%3D%3D)

**Comment by sizuhiko** [comment]
#13 #14 #15 #16 へ分割した
